# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dry-monitor` gem.
# Please instead update this file by running `bin/tapioca gem dry-monitor`.

# source://dry-monitor//lib/dry/monitor/version.rb#3
module Dry
  class << self
    # source://dry-auto_inject/1.0.0/lib/dry/auto_inject.rb#61
    def AutoInject(container, options = T.unsafe(nil)); end

    # source://dry-cli/1.0.0/lib/dry/cli.rb#221
    def CLI(registry_or_command = T.unsafe(nil), &block); end

    # source://dry-configurable/1.0.1/lib/dry/configurable.rb#11
    def Configurable(**options); end

    # source://dry-core/1.0.0/lib/dry/core.rb#41
    def Equalizer(*keys, **options); end
  end
end

# source://dry-monitor//lib/dry/monitor/version.rb#4
module Dry::Monitor
  include ::Dry::Core::Constants
  extend ::Dry::Core::Extensions

  class << self
    # @api private
    #
    # source://dry-monitor//lib/dry/monitor.rb#24
    def loader; end
  end
end

# source://dry-monitor//lib/dry/monitor/notifications.rb#7
Dry::Monitor::CLOCK = T.let(T.unsafe(nil), Dry::Monitor::Clock)

# @api public
#
# source://dry-monitor//lib/dry/monitor/clock.rb#6
class Dry::Monitor::Clock
  # @api private
  # @return [Clock] a new instance of Clock
  #
  # source://dry-monitor//lib/dry/monitor/clock.rb#8
  def initialize(unit: T.unsafe(nil)); end

  # @api public
  #
  # source://dry-monitor//lib/dry/monitor/clock.rb#20
  def current; end

  # @api public
  #
  # source://dry-monitor//lib/dry/monitor/clock.rb#13
  def measure; end
end

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::EMPTY_ARRAY = T.let(T.unsafe(nil), Array)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::EMPTY_OPTS = T.let(T.unsafe(nil), Hash)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::EMPTY_SET = T.let(T.unsafe(nil), Set)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::EMPTY_STRING = T.let(T.unsafe(nil), String)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::IDENTITY = T.let(T.unsafe(nil), Proc)

# source://dry-monitor//lib/dry/monitor/logger.rb#7
class Dry::Monitor::Logger < ::Logger
  # @return [Logger] a new instance of Logger
  #
  # source://dry-monitor//lib/dry/monitor/logger.rb#12
  def initialize(*args); end
end

# source://dry-monitor//lib/dry/monitor/logger.rb#8
Dry::Monitor::Logger::DEFAULT_FORMATTER = T.let(T.unsafe(nil), Proc)

# source://dry-monitor//lib/dry/monitor/notifications.rb#9
class Dry::Monitor::Notifications
  include ::Dry::Core::Constants
  include ::Dry::Events::Publisher::InstanceMethods
  extend ::Dry::Events::Publisher::ClassMethods

  # @return [Notifications] a new instance of Notifications
  #
  # source://dry-monitor//lib/dry/monitor/notifications.rb#15
  def initialize(id, clock: T.unsafe(nil)); end

  # Returns the value of attribute clock.
  #
  # source://dry-monitor//lib/dry/monitor/notifications.rb#13
  def clock; end

  # Returns the value of attribute id.
  #
  # source://dry-monitor//lib/dry/monitor/notifications.rb#13
  def id; end

  # source://dry-monitor//lib/dry/monitor/notifications.rb#28
  def instrument(event_id, payload = T.unsafe(nil), &block); end

  # source://dry-monitor//lib/dry/monitor/notifications.rb#20
  def start(event_id, payload); end

  # source://dry-monitor//lib/dry/monitor/notifications.rb#24
  def stop(event_id, payload); end
end

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::Notifications::EMPTY_ARRAY = T.let(T.unsafe(nil), Array)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::Notifications::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::Notifications::EMPTY_OPTS = T.let(T.unsafe(nil), Hash)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::Notifications::EMPTY_SET = T.let(T.unsafe(nil), Set)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::Notifications::EMPTY_STRING = T.let(T.unsafe(nil), String)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::Notifications::IDENTITY = T.let(T.unsafe(nil), Proc)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::Notifications::Self = T.let(T.unsafe(nil), Proc)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::Notifications::Undefined = T.let(T.unsafe(nil), Object)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::Self = T.let(T.unsafe(nil), Proc)

# source://dry-core/1.0.0/lib/dry/core/constants.rb#112
Dry::Monitor::Undefined = T.let(T.unsafe(nil), Object)

# source://dry-monitor//lib/dry/monitor/version.rb#5
Dry::Monitor::VERSION = T.let(T.unsafe(nil), String)
