# typed: true
# frozen_string_literal: true

require 'bundler/setup'
require 'dotenv'
require 'dry/cli'
require 'dry/configurable'
require 'dry/struct'
require 'dry/system'
require 'dry/system/container'
require 'dry/types'
require 'forwardable'
require 'irb'
require 'net/http'
require 'openstory/core'
require 'openstory/plurk'
require 'openstory/support/pipeline'
require 'pry'
require 'simplecov'
require 'simplecov-cobertura'
require 'singleton'
