# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Pry; end
module Concurrent::Hash; end
module Concurrent::Map; end
module Gem::Ext::BuildError; end
module OpenStory::Types::Integer; end
module OpenStory::Types::String; end
