name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: '3.1.3'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version:  ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run Rubocop
      run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rake

  cucumber:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run Cucumber
      run: bundle exec cucumber
