name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: '3.1.3'
  PLURK_APP_KEY: ''
  PLURK_APP_SECRET: ''
  PLURK_ACCESS_TOKEN: ''
  PLURK_SECRET_TOKEN: ''

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version:  ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run Rubocop
      run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rspec
    - name: Archive RSpec coverage report
      uses: actions/upload-artifact@v3
      with:
        name: simplecov-resultset-rspec
        path: coverage/
        retention-days: 1

  cucumber:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run Cucumber
      run: bundle exec cucumber
    - name: Archive Cucumber coverage report
      uses: actions/upload-artifact@v3
      with:
        name: simplecov-resultset-cucumber
        path: coverage/
        retention-days: 1

  report-coverage:
    runs-on: ubuntu-latest
    needs:
      - simplecov-resultset-rspec
      - simplecov-resultset-cucumber
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Download RSpec coverage report
        uses: actions/download-artifact@v3
        with:
          name: simplecov-resultset-rspec
          path: simplecov-resultset-rspec/
    - name: Download Cucumber coverage report
        uses: actions/download-artifact@v3
        with:
          name: simplecov-resultset-cucumber
          path: simplecov-resultset-cucumber/
    - name: Upload coverage report
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: bundle exec rake coverage:report
